name: Autograding

on: [push]

permissions:
  contents: read
  checks: write
  issues: write
  pull-requests: write
  actions: write

jobs:
  Autograding:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Chocolatey
        shell: powershell
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force; \
          [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; \
          iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))

      - name: Install Office
        shell: powershell
        run: choco install office365business -y

      - name: Run Autograding
        uses: education/autograding@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
